# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use
# ===================================================================

spring:
    application:
        name: kothamala