# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

spring:
    profiles:
        name: dev

server:
    port: 8080