-- MySQL Script generated by MySQL Workbench
-- 01/08/17 23:17:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kothamala_rough
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kothamala_rough
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kothamala_rough` DEFAULT CHARACTER SET utf8 ;
USE `kothamala_rough` ;

-- -----------------------------------------------------
-- Table `kothamala_rough`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `mobile` VARCHAR(50) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `password_hash` VARCHAR(60) NOT NULL,
  `activation_key` VARCHAR(20) NULL,
  `avatar` VARCHAR(45) NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(45) NULL,
  `last_modified_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(10) NOT NULL,
  `like_count` INT NULL,
  `dislike_count` INT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(45) NULL,
  `last_modified_date` DATETIME NULL,
  `comment_count` INT NULL,
  `user_id` INT NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `post_text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kothamala_rough`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`comment` (
  `id` INT NOT NULL,
  `status` VARCHAR(10) NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(45) NULL,
  `last_modified_date` DATETIME NULL,
  `parent_comment_id` INT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `comment_text` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_post1_idx` (`post_id` ASC),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `kothamala_rough`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kothamala_rough`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`vote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isLike` BIT NOT NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(45) NULL,
  `last_modified_date` DATETIME NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vote_post1_idx` (`post_id` ASC),
  INDEX `fk_vote_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_vote_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `kothamala_rough`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kothamala_rough`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`tag` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(45) NULL,
  `last_modified_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `created_by` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_by` VARCHAR(45) NULL,
  `last_modified_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`user_has_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_id`),
  INDEX `fk_user_has_role_role1_idx` (`role_id` ASC),
  INDEX `fk_user_has_role_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `kothamala_rough`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `kothamala_rough`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kothamala_rough`.`post_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kothamala_rough`.`post_has_tag` (
  `post_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `tag_id`),
  INDEX `fk_post_has_tag_tag1_idx` (`tag_id` ASC),
  INDEX `fk_post_has_tag_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_post_has_tag_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `kothamala_rough`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_has_tag_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `kothamala_rough`.`tag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
